#ifndef CS2_RADAR_CONFIG
#define CS2_RADAR_CONFIG

#define REFRESH_RATE 20 // refresh rate in Hz
#define REFRESH_INTERVAL 1000 / REFRESH_RATE

#define PROCESS_NAME "cs2"
#define CLIENT_LIB "libclient.so"
#define ENGINE_LIB "libengine2.so"
#define TIER0_LIB "libtier0.so"

#define ENTITY_OFFSET 0x50

#define ELF_MACHINE_TYPE 0x12
#define ELF_MACHINE_x64 0x3E

#ifdef __x86_64__
#define ELF_PROGRAM_HEADER_OFFSET 0x20
#define ELF_PROGRAM_HEADER_ENTRY_SIZE 0x36
#define ELF_PROGRAM_HEADER_NUM_ENTRIES 0x38

#define ELF_SECTION_HEADER_OFFSET 0x28
#define ELF_SECTION_HEADER_ENTRY_SIZE 0x3A
#define ELF_SECTION_HEADER_NUM_ENTRIES 0x3C

#else
#define ELF_PROGRAM_HEADER_OFFSET 0x1C
#define ELF_PROGRAM_HEADER_ENTRY_SIZE 0x2A
#define ELF_PROGRAM_HEADER_NUM_ENTRIES 0x2C

#define ELF_SECTION_HEADER_OFFSET 0x20
#define ELF_SECTION_HEADER_ENTRY_SIZE 0x2E
#define ELF_SECTION_HEADER_NUM_ENTRIES 0x30

#endif

#define ELF_DYNAMIC_SECTION 0x02

#endif
